// make-signature [package dir] — reads <dir>/signature.json, checks every pair the kit draws, and only
// when none fails writes <dir>/src/index.ts (the Signature, typed against the installed theme) and
// <dir>/assets/*.svg. Run before tsc in a signature package: `make-signature && tsc && gen-signature`.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { checkContrast, makeSignature, readSignatureInput } from './index.js';

const dir = resolve(process.argv[2] ?? '.');
const input = readSignatureInput(JSON.parse(readFileSync(join(dir, 'signature.json'), 'utf8')));
const kit = makeSignature(input);
const pairs = checkContrast(kit.signature, kit.paints);

const line = (p: (typeof pairs)[number]) => `${p.pair} (${p.mode}): ${p.ratio}:1, needs ${p.minimum}:1`;
const failures = pairs.filter((p) => p.status === 'fail');
if (failures.length) {
  for (const p of failures) console.error(`[make-signature] ${input.id}: FAILS ${line(p)}`);
  process.exit(1);
}

mkdirSync(join(dir, 'src'), { recursive: true });
mkdirSync(join(dir, 'assets'), { recursive: true });
writeFileSync(
  join(dir, 'src', 'index.ts'),
  `// GENERATED by make-signature from signature.json. Edit signature.json and rebuild.
import type { Signature } from '@digitaplatform/theme';

export const signature: Signature = ${JSON.stringify(kit.signature, null, 2)};

export default signature;
`,
);
for (const [name, svg] of Object.entries(kit.assets)) writeFileSync(join(dir, 'assets', name), `${svg}\n`);
console.log(`[make-signature] ${input.id}: all ${pairs.length} pairs pass AA → src/index.ts + ${Object.keys(kit.assets).length} assets`);
