import {
  Activity,
  AlertTriangle,
  Archive,
  Badge,
  BadgePercent,
  Banknote,
  Book,
  BookOpen,
  BoxSelect,
  Boxes,
  Building,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ClipboardCheck,
  ClipboardList,
  ClipboardPenLine,
  ClockArrowDown,
  Coins,
  Factory,
  FileDown,
  FileInput,
  FileText,
  FolderKanban,
  Globe,
  History,
  Landmark,
  Layers,
  Layers3,
  Library,
  List,
  ListChecks,
  ListOrdered,
  ListTree,
  MailQuestion,
  Map as MapIcon,
  Menu,
  Move3d,
  Package,
  Package2,
  PackageCheck,
  PackageSearch,
  Percent,
  Puzzle,
  QrCode,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  RotateCw,
  Ruler,
  ScrollText,
  Settings,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Tags,
  Target,
  Truck,
  Undo2,
  UserRound,
  Users,
  UsersRound,
  View,
  Wallet,
  Wrench,
  Circle,
  type LucideIcon,
} from 'lucide-react';

/**
 * Curated kebab-name → lucide component map for the nav icons the app's menu
 * seed uses. Named imports (tree-shaken) keep the plugin bundle tiny vs a
 * namespace import of all ~1500 icons. Unknown names fall back to `Circle`.
 */
export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  badge: Badge,
  'badge-percent': BadgePercent,
  banknote: Banknote,
  book: Book,
  'book-open': BookOpen,
  'box-select': BoxSelect,
  boxes: Boxes,
  building: Building,
  'building-2': Building2,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clipboard-pen-line': ClipboardPenLine,
  'clock-arrow-down': ClockArrowDown,
  coins: Coins,
  factory: Factory,
  'file-down': FileDown,
  'file-input': FileInput,
  'file-text': FileText,
  'folder-kanban': FolderKanban,
  globe: Globe,
  history: History,
  landmark: Landmark,
  layers: Layers,
  'layers-3': Layers3,
  library: Library,
  list: List,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  'list-tree': ListTree,
  'mail-question': MailQuestion,
  map: MapIcon,
  menu: Menu,
  'move-3d': Move3d,
  package: Package,
  'package-2': Package2,
  'package-check': PackageCheck,
  'package-search': PackageSearch,
  percent: Percent,
  puzzle: Puzzle,
  'qr-code': QrCode,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  'scroll-text': ScrollText,
  settings: Settings,
  ship: Ship,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  tags: Tags,
  target: Target,
  truck: Truck,
  'undo-2': Undo2,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  view: View,
  wallet: Wallet,
  wrench: Wrench,
};

export const FALLBACK_ICON: LucideIcon = Circle;
