#!/usr/bin/env node
// Asset files are editable; src/assets.ts is generated before the build.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(join(pkgDir, rel), 'utf8').trim();
const oneLine = (svg) => svg.replace(/\r?\n\s*/g, ' ');
function toCssUrl(rel, { stretch = false } = {}) {
  let svg = read(rel);
  if (stretch) {
    svg = svg.replace(
      /<svg([^>]*?)\s+width="[^"]*"\s+height="[^"]*"/,
      '<svg$1 preserveAspectRatio="none"',
    );
  }
  return `url("data:image/svg+xml,${encodeURIComponent(oneLine(svg))}")`;
}

const GRAPHICS = {
  grid: {
    light: toCssUrl('assets/backgrounds/simetrix-grid-overlay-light.svg'),
    dark: toCssUrl('assets/backgrounds/simetrix-grid-overlay-dark.svg'),
  },
  glow: {
    light: toCssUrl('assets/backgrounds/simetrix-glow-light.svg'),
    dark: toCssUrl('assets/backgrounds/simetrix-glow-dark.svg'),
  },
  card: {
    light: toCssUrl('assets/backgrounds/simetrix-card-light.svg', { stretch: true }),
    dark: toCssUrl('assets/backgrounds/simetrix-card-dark.svg', { stretch: true }),
  },
  panel: {
    light: toCssUrl('assets/backgrounds/simetrix-panel-contact-light.svg', { stretch: true }),
    dark: toCssUrl('assets/backgrounds/simetrix-panel-contact-dark.svg', { stretch: true }),
  },
};

const fields = {
  APPICON_SVG: read('assets/simplidigita-appicon.svg'),
  MONOGRAM_SVG: read('assets/simplidigita-mark.svg'),
  WORDMARK_SVG: read('assets/simplidigita-wordmark.svg'),
};
writeFileSync(join(pkgDir, 'src/assets.ts'),
  '// GENERATED by scripts/gen-assets.mjs; edit assets/, then rebuild.\n' +
  Object.entries(fields).map(([key, value]) => `export const ${key} = ${JSON.stringify(value)};`).join('\n') +
  `\nexport const GRAPHICS = ${JSON.stringify(GRAPHICS, null, 2)};\n`
);
