#!/usr/bin/env node
// gen-assets — inlines the digita brand ASSET FILES (assets/*) into a generated
// TS module (src/assets.ts) so the compiled Signature config carries them
// verbatim (the plugin-delivery model inlines everything into
// dist/digita-plugin.json). The FILES in assets/ are the single editable source
// of truth — this script only derives, never invents:
//   - digita-cloud-appicon.svg  → APPICON_SVG (verbatim) and MONOGRAM_SVG (the
//     same icon adapted for inline chrome use: root width/height stripped so CSS
//     sizes it, ids namespaced `dgc-` against host-page collisions, aria-hidden).
//   - digita-cloud-wordmark.svg → WORDMARK_SVG (verbatim).
//   - graphics.json             → GRAPHICS (the {light,dark} background layers).
//   - fonts.css                 → GOOGLE_FONTS_URL + GOOGLE_FONTS_LINKS (the
//     exact <link> tags from digitacloud.app.dc.html:11-13, incl. preconnects).
// Run before tsc: `node ./scripts/gen-assets.mjs && tsc && gen-signature`.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(join(pkgDir, rel), 'utf8').trim();

const appicon = read('assets/digita-cloud-appicon.svg');
const wordmark = read('assets/digita-cloud-wordmark.svg');
const graphics = JSON.parse(read('assets/graphics.json'));

// MONOGRAM: the app icon, adapted for inline <html> use. Strip the fixed
// width/height from the root (the consumer sizes via CSS, viewBox preserved),
// add aria-hidden (decorative — the chrome supplies the accessible name), and
// namespace every id (a raster-fixed id like "glow" would collide with other
// inlined SVGs on the same page; first-id-wins would corrupt the gradients).
let monogram = appicon
  .replace(/<svg([^>]*?)\s+width="[^"]*"\s+height="[^"]*"/, '<svg$1')
  .replace(/<svg /, '<svg aria-hidden="true" ');
for (const id of [...new Set([...monogram.matchAll(/\bid="([^"]+)"/g)].map((m) => m[1]))]) {
  monogram = monogram
    .replaceAll(`id="${id}"`, `id="dgc-${id}"`)
    .replaceAll(`url(#${id})`, `url(#dgc-${id})`);
}
// Collapse the pretty-printed source to one line for the inline string.
monogram = monogram.replace(/\r?\n\s*/g, '');

const fontsCss = read('assets/fonts.css');
const urlMatch = /@import url\('([^']+)'\)/.exec(fontsCss);
if (!urlMatch) throw new Error('[gen-assets] assets/fonts.css: no @import url(...) found.');
const fontsUrl = urlMatch[1];
// The exact tags from the template <helmet> (digitacloud.app.dc.html:11-13).
const fontsLinks = [
  '<link rel="preconnect" href="https://fonts.googleapis.com">',
  '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
  `<link href="${fontsUrl}" rel="stylesheet">`,
].join('\n');

const banner = `// GENERATED by scripts/gen-assets.mjs from the files in assets/ — DO NOT EDIT.
// Edit the asset files (the single source of truth) and rebuild.`;
const lit = (s) => JSON.stringify(s);

writeFileSync(
  join(pkgDir, 'src', 'assets.ts'),
  `${banner}

/** The real digita-cloud app icon (assets/digita-cloud-appicon.svg), verbatim. */
export const APPICON_SVG = ${lit(appicon)};

/** The app icon adapted for inline brand-chrome use: no fixed width/height
 *  (CSS sizes it, viewBox intact), ids namespaced \`dgc-\`, aria-hidden. */
export const MONOGRAM_SVG = ${lit(monogram)};

/** The "digita●cloud" wordmark lockup (assets/digita-cloud-wordmark.svg), verbatim. */
export const WORDMARK_SVG = ${lit(wordmark.replace(/\r?\n\s*/g, ''))};

/** The decorative background layers (assets/graphics.json): {light,dark} CSS
 *  values for grid / glow / band / card / panel, exact from the templates. */
export const GRAPHICS: Record<'grid' | 'glow' | 'band' | 'card' | 'panel', { light: string; dark: string }> =
  ${JSON.stringify(graphics, null, 2).replace(/\n/g, '\n  ')};

/** The exact Google-Fonts CSS URL (assets/fonts.css). */
export const GOOGLE_FONTS_URL = ${lit(fontsUrl)};

/** The exact <link> tags from the template helmet (preconnects + stylesheet)
 *  for apps that load the fonts from index.html instead of bundled CSS. */
export const GOOGLE_FONTS_LINKS = ${lit(fontsLinks)};
`,
);
console.log('[gen-assets] assets/* → src/assets.ts');
